### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by eXConf** [eXConf/homepage#5]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by alter-exo** [comment]
<h2>Résumé</h2>
<p>&mdash; I'm a time traveller and universe explorer. If something interesting is being started somewhere - be sure to find me there! With my TARDIS I always come just in time and my knowledge in science, technologies and history collected over the centuries always come in handy when you need to solve another omg-we-are-all-gonna-die problem.</p>
