### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by eXConf** [eXConf/homepage#6]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by alter-exo** [comment]
Twitter: https://twitter.com/bbcdoctorwho
FB: https://www.facebook.com/DoctorWho
Wikipedia: https://en.wikipedia.org/wiki/The_Doctor_(Doctor_Who)
IMDB: https://www.imdb.com/title/tt0436992/?ref_=fn_al_tt_1
