### ISSUE TITLE
Составить таймлайн

### ISSUE THREAD

**Issue by eXConf** [eXConf/homepage#7]
Составить список всех (важных) жизненных событий, памятных дат, достижений, периодов, которые дали приятный и неприятный опыт, и т.п. В этом конкретном случае длинных списков не бывает, бывают плохо свернутые, поэтому пакуем сюда всё подряд, а про "лишние" события можно будет промолчать позже. Список должен быть систематизирован и отсортирован таким образом, чтоб читатель быстро понял "паттерн" и мог легко ориентироваться в пространстве и времени этого резюме.

**Comment by alter-exo** [comment]
2059 Stopped the zombie infection on Mars... at the price of the first human colony
2012 Managed to figure out what caused people to disappear on the day of the opening ceremony of the 2012 Olympic Games in London
2007 Had to deal with consequences of a mad scientist's experiment
2006 Revealed the Slitheen plan on unleashing the World War III
2005 Put an end to Sycorax invasion and saved the Christmas
1969 Escaped from the Weeping Angels trap (hate these things!)
1953 Stopped an alien calling itself 'The Wire' from consuming humans
1941 Solved the mystery of so called 'empty child' in London
1930 Daleks were kidnapping homeless humans - not on my watch!
1926 Solved the crime with Agatha Christie
1913 Double-crossed and captured The Family
1879 Saved the Queen Victoria from lycanthropy infection
1869 Stopped gas-like creatures named from capturing human bodies in Cardiff
1851 Once again stopped the Cybermen invasion
1599 Helped Shakespeare to stay in a state of 'to be' (aka saved his life)
79 Survived the Eruption of Mount Vesuvius
